# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GOROOT: /usr/local/go
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
        
    - name: Install dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Checkout goqu repository
      run: |
        cd ./src/github.com/doug-martin/
        git clone https://github.com/doug-martin/goqu.git v9

    - name: Checkout godotenv repository
      run: |
        cd ./src/github.com/joho/
        git clone https://github.com/joho/godotenv.git

    - name: Checkout gorilla/mux repository
      run: |
        cd ./src/github.com/gorilla/
        git clone https://github.com/gorilla/mux.git
        
    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...
